# Generated by Django 5.0.4 on 2024-06-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_team_person_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
